spring.application.name=springrest

spring.datasource.url=jdbc:postgresql://localhost:5432/SpringRest
spring.datasource.username=postgres
spring.datasource.password=Awsys123

spring.jpa.hibernate.ddl-auto=update