spring.application.name=springrest

spring.datasource.url=jdbc:postgresql://localhost:5432/SpringRest
spring.datasource.username=postgres
spring.datasource.password=Awsys123

spring.jpa.hibernate.ddl-auto=update

#spring.security.user.name=user
#spring.security.user.password=Awsys123

logging.level.org.springframework.boot.security.autoconfigure=INFO
